#!/usr/bin/env python3
"""
MCP SSE Handler for Neural Memory Graph
Implements Model Context Protocol with Server-Sent Events
"""

from flask import Response, request, jsonify, stream_with_context
import json
import hashlib
import hmac
import os

from database import get_stats, get_node, delete_node as db_delete_node, update_node as db_update_node, get_note_history, restore_note_version
from graph_engine import add_note_with_links
from websocket_events import broadcast_note_added, broadcast_note_updated, broadcast_note_deleted, broadcast_search
from graph_engine import search_with_activation, get_node_graph, search_with_activation_protected, find_similar_notes
from stable_embeddings import get_model

# Authentication - use environment variable
API_KEY = os.getenv("NEURAL_API_KEY", "change_me_in_production")
API_KEY_HASH = hashlib.sha256(API_KEY.encode()).hexdigest()


def verify_auth(req):
    """Verify API key from URL parameter or Authorization header"""
    url_key = req.args.get("api_key")
    if url_key:
        key_hash = hashlib.sha256(url_key.encode()).hexdigest()
        return hmac.compare_digest(key_hash, API_KEY_HASH)
    
    auth_header = req.headers.get("Authorization")
    if auth_header and auth_header.startswith("Bearer "):
        token = auth_header[7:]
        token_hash = hashlib.sha256(token.encode()).hexdigest()
        return hmac.compare_digest(token_hash, API_KEY_HASH)
    
    return False


def handle_mcp_request(method, params):
    """Route MCP requests to handlers"""
    try:
        if method == "initialize":
            return {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {"name": "hippograph", "version": "2.0.0"}
            }
        elif method == "tools/list":
            return {"tools": get_tools_list()}
        elif method == "tools/call":
            return handle_tool_call(params)
        return {"error": {"code": -32601, "message": f"Method not found: {method}"}}
    except Exception as e:
        return {"error": {"code": -32603, "message": str(e)}}


def get_tools_list():
    """Return list of available MCP tools"""
    tools = [
        {
            "name": "search_memory",
            "description": "Search through notes using spreading activation algorithm",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Search query"},
                    "limit": {"type": "integer", "default": 5, "minimum": 1, "maximum": 20},
                    "category": {"type": "string", "description": "Optional: filter results by category (e.g., 'breakthrough', 'technical')"},
                    "time_after": {"type": "string", "description": "Optional: only return notes created after this datetime (ISO format: '2026-01-01T00:00:00')"},
                    "time_before": {"type": "string", "description": "Optional: only return notes created before this datetime (ISO format: '2026-02-01T00:00:00')"},
                    "entity_type": {"type": "string", "description": "Optional: only return notes containing entities of this type (e.g., 'person', 'organization', 'concept', 'location', 'tech')"},
                    "max_results": {"type": "integer", "default": 10, "minimum": 1, "maximum": 50, "description": "Hard limit on results (prevents context overflow)"},
                    "detail_mode": {"type": "string", "enum": ["brief", "full"], "default": "full", "description": "brief: first line + metadata, full: complete content"}
                },
                "required": ["query"]
            }
        },
        {
            "name": "add_note",
            "description": "Add new note with automatic entity extraction, linking, and emotional context. Checks for duplicates.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Note content"},
                    "category": {"type": "string", "default": "general"},
                    "importance": {"type": "string", "enum": ["critical", "normal", "low"], "default": "normal", "description": "Note importance level"},
                    "force": {"type": "boolean", "default": False, "description": "Force add even if duplicate exists"},
                    "emotional_tone": {"type": "string", "description": "Keywords describing emotional tone (e.g., 'joy, validation, trust')"},
                    "emotional_intensity": {"type": "integer", "default": 5, "minimum": 0, "maximum": 10, "description": "Emotional intensity from 0 (none) to 10 (very strong)"},
                    "emotional_reflection": {"type": "string", "description": "Narrative reflection on emotional context"},
                    "tags": {"type": "string", "description": "Space-separated searchable tags (why, what, keywords). Generated by AI at write time to improve retrieval."}
                },
                "required": ["content"]
            }
        },
        {
            "name": "update_note",
            "description": "Update existing note by ID",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "note_id": {"type": "integer"},
                    "content": {"type": "string"},
                    "category": {"type": "string"}
                },
                "required": ["note_id", "content"]
            }
        },
        {
            "name": "delete_note",
            "description": "Delete note by ID",
            "inputSchema": {
                "type": "object",
                "properties": {"note_id": {"type": "integer"}},
                "required": ["note_id"]
            }
        },
        {
            "name": "neural_stats",
            "description": "Get statistics about stored notes, edges, and entities",
            "inputSchema": {"type": "object", "properties": {}}
        },
        {
            "name": "get_graph",
            "description": "Get graph connections for a specific note",
            "inputSchema": {
                "type": "object",
                "properties": {"note_id": {"type": "integer"}},
                "required": ["note_id"]
            }
        },
        {
            "name": "set_importance",
            "description": "Set importance level for a note: 'critical' (2x boost), 'normal', or 'low' (0.5x)",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "note_id": {"type": "integer"},
                    "importance": {"type": "string", "enum": ["critical", "normal", "low"]}
                },
                "required": ["note_id", "importance"]
            }
        },
        {
            "name": "find_similar",
            "description": "Find notes similar to given content. Useful for checking before adding new notes.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Content to find similar notes for"},
                    "threshold": {"type": "number", "default": 0.7, "description": "Minimum similarity (0-1)"},
                    "limit": {"type": "integer", "default": 5}
                },
                "required": ["content"]
            }
        },
        {
            "name": "get_note_history",
            "description": "Get version history for a note",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "note_id": {"type": "integer"},
                    "limit": {"type": "integer", "default": 5}
                },
                "required": ["note_id"]
            }
        },
        {
            "name": "restore_note_version",
            "description": "Restore a note to a previous version",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "note_id": {"type": "integer"},
                    "version_number": {"type": "integer"}
                },
                "required": ["note_id", "version_number"]
            }
        },
        {
            "name": "search_stats",
            "description": "Get search quality monitoring stats: latency percentiles, zero-result queries, phase breakdown. Helps identify retrieval issues.",
            "inputSchema": {"type": "object", "properties": {}}
        },
        {
            "name": "sleep_compute",
            "description": "Run sleep-time graph maintenance: consolidation (thematic clusters + temporal chains), PageRank recalculation, orphan detection, stale edge decay, duplicate scan. Zero LLM cost. Use dry_run=true to preview without changes.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "dry_run": {
                        "type": "boolean",
"default": False,
                        "description": "If true, report only without making changes"
                    }
                }
            }
        },
        {
            "name": "list_entity_candidates",
            "description": "List entity merge candidates (read-only). Shows case variants like git/Git/GIT grouped by normalized name and type.",
            "inputSchema": {"type": "object", "properties": {}}
        },
        {
            "name": "merge_entities",
            "description": "Merge two entity nodes: transfer all graph links from remove_id to keep_id, then delete remove_id. Use list_entity_candidates first to find candidates. IRREVERSIBLE - take snapshot first.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "keep_id": {"type": "integer", "description": "Entity ID to keep"},
                    "remove_id": {"type": "integer", "description": "Entity ID to remove (links transferred to keep_id)"}
                },
                "required": ["keep_id", "remove_id"]
            }
        }
    ]
    # Extend with anchor policy tools
    tools += [
        {
            "name": "list_anchor_policies",
            "description": "List all anchor policies: hardcoded (system baseline, cannot be removed) + user-defined. Protected categories are exempt from stale edge decay and kept at critical importance.",
            "inputSchema": {"type": "object", "properties": {}}
        },
        {
            "name": "add_anchor_policy",
            "description": "Add a user-defined anchor policy: protect a category from stale edge decay and keep notes at critical importance. Supplements hardcoded baseline.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "category": {"type": "string", "description": "Note category to protect (e.g. 'project-decisions')"},
                    "description": {"type": "string", "description": "Optional: why this category is important"}
                },
                "required": ["category"]
            }
        },
        {
            "name": "remove_anchor_policy",
            "description": "Remove a user-defined anchor policy. Cannot remove hardcoded system categories (anchor, self-reflection, etc).",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "category": {"type": "string", "description": "Category to unprotect"}
                },
                "required": ["category"]
            }
        }
    ]
    tools += [
        {
            "name": "ingest_skill",
            "description": "Ingest a skill from text/file into memory graph. Security scan runs automatically. First call returns preview + scan results. Call again with confirmed=True to add to memory.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Raw skill content (SKILL.md text or description)"},
                    "source": {"type": "string", "description": "Source URL or file path for auditability"},
                    "confirmed": {"type": "boolean", "default": False, "description": "Set True after reviewing preview to actually add to memory"}
                },
                "required": ["content"]
            }
        }
    ]

    tools += [
        {
            "name": "update_working_memory",
            "description": "Update working memory with current session context. Called by AI as part of inference when something significant happens (decision made, task completed, important context learned). Overwrites previous working memory for this session.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Current session context: what we are doing, key decisions, active tasks"},
                    "session_id": {"type": "string", "description": "Optional session identifier", "default": "current"}
                },
                "required": ["content"]
            }
        }
    ]
    return tools


def handle_tool_call(params):
    """Execute tool calls"""
    tool_name = params.get("name")
    args = params.get("arguments", {})
    
    if tool_name == "search_memory":
        return tool_search_memory(
            args.get("query", ""), 
            args.get("limit", 5),
            args.get("max_results", 10),
            args.get("detail_mode", "full"),
            args.get("category", None),
            args.get("time_after", None),
            args.get("time_before", None),
            args.get("entity_type", None)
        )
    elif tool_name == "add_note":
        return tool_add_note(
            args.get("content", ""), 
            args.get("category", "general"),
            args.get("importance", "normal"),
            args.get("force", False),
            args.get("emotional_tone", None),
            args.get("emotional_intensity", 5),
            args.get("emotional_reflection", None),
            args.get("tags", None)
        )
    elif tool_name == "update_note":
        return tool_update_note(args.get("note_id"), args.get("content"), args.get("category"))
    elif tool_name == "delete_note":
        return tool_delete_note(args.get("note_id"))
    elif tool_name == "neural_stats":
        return tool_stats()
    elif tool_name == "get_graph":
        return tool_get_graph(args.get("note_id"))
    elif tool_name == "set_importance":
        return tool_set_importance(args.get("note_id"), args.get("importance"))
    elif tool_name == "find_similar":
        return tool_find_similar(args.get("content", ""), args.get("threshold", 0.7), args.get("limit", 5))
    
    elif tool_name == "get_note_history":
        return tool_get_note_history(args.get("note_id"), args.get("limit", 5))
    elif tool_name == "restore_note_version":
        return tool_restore_note_version(args.get("note_id"), args.get("version_number"))
    elif tool_name == "search_stats":
        return tool_search_stats()
    elif tool_name == "sleep_compute":
        return tool_sleep_compute(args.get("dry_run", False))
    elif tool_name == "list_entity_candidates":
        return tool_list_entity_candidates()
    elif tool_name == "merge_entities":
        return tool_merge_entities(args.get("keep_id"), args.get("remove_id"))
    elif tool_name == "list_anchor_policies":
        return tool_list_anchor_policies()
    elif tool_name == "add_anchor_policy":
        return tool_add_anchor_policy(args.get("category", ""), args.get("description", ""))
    elif tool_name == "remove_anchor_policy":
        return tool_remove_anchor_policy(args.get("category", ""))
    elif tool_name == "update_working_memory":
        return tool_update_working_memory(args.get("content", ""), args.get("session_id", "current"))
    elif tool_name == "ingest_skill":
        return tool_ingest_skill(args.get("content", ""), args.get("source", ""), args.get("confirmed", False))
    
    return {"error": {"code": -32602, "message": f"Unknown tool: {tool_name}"}}


def tool_search_memory(query: str, limit: int, max_results: int = 10, detail_mode: str = "full", category: str = None, 
                      time_after: str = None, time_before: str = None, entity_type: str = None):
    """Search with spreading activation and optional filters (category, time range, entity type)"""
    # 15e: dateparser - parse relative temporal expressions if time_after/time_before not set
    if not time_after and not time_before:
        try:
            import dateparser
            from datetime import datetime, timedelta
            import re
            query_lower = query.lower()
            now = datetime.now()
            # Patterns: last week, last month, yesterday, today, last N days
            if re.search(r'last week|\u043f\u0440\u043e\u0448\u043b', query_lower):
                time_after = (now - timedelta(days=7)).isoformat()
            elif re.search(r'last month|\u043f\u0440\u043e\u0448\u043b.*\u043c\u0435\u0441', query_lower):
                time_after = (now - timedelta(days=30)).isoformat()
            elif re.search(r'yesterday|\u0432\u0447\u0435\u0440\u0430', query_lower):
                time_after = (now - timedelta(days=1)).replace(hour=0, minute=0, second=0).isoformat()
                time_before = now.replace(hour=0, minute=0, second=0).isoformat()
            elif re.search(r'today|\u0441\u0435\u0433\u043e\u0434\u043d\u044f', query_lower):
                time_after = now.replace(hour=0, minute=0, second=0).isoformat()
            elif m := re.search(r'last (\d+) days?', query_lower):
                days = int(m.group(1))
                time_after = (now - timedelta(days=days)).isoformat()
            if time_after:
                print(f"📅 dateparser: time_after={time_after[:10]} (from query: {query!r})")
        except Exception as e:
            print(f"⚠️  dateparser skipped: {e}")
    response = search_with_activation_protected(
        query=query,
        limit=limit,
        max_results=max_results,
        detail_mode=detail_mode,
        category_filter=category,
        time_after=time_after,
        time_before=time_before,
        entity_type_filter=entity_type
    )
    
    results = response["results"]
    metadata = response["metadata"]
    
    if not results:
        filters = []
        if category:
            filters.append(f"category: {category}")
        if time_after:
            filters.append(f"after: {time_after[:10]}")
        if time_before:
            filters.append(f"before: {time_before[:10]}")
        if entity_type:
            filters.append(f"entity_type: {entity_type}")
        
        if filters:
            text = f"No results found for: {query} ({', '.join(filters)})"
        else:
            text = f"No results found for: {query}"
    else:
        filters_desc = []
        if category:
            filters_desc.append(f"category '{category}'")
        if time_after or time_before:
            if time_after and time_before:
                filters_desc.append(f"{time_after[:10]} to {time_before[:10]}")
            elif time_after:
                filters_desc.append(f"after {time_after[:10]}")
            elif time_before:
                filters_desc.append(f"before {time_before[:10]}")
        if entity_type:
            filters_desc.append(f"entity_type '{entity_type}'")
        
        if filters_desc:
            text = f"Found {len(results)} notes ({', '.join(filters_desc)}):\n\n"
        else:
            text = f"Found {len(results)} notes:\n\n"
            
        for r in results:
            if "first_line" in r:
                # Brief mode
                importance_tag = f" ⭐{r['importance']}" if r.get('importance') != 'normal' else ""
                emotion_tag = f" 💭{r['emotional_tone']}" if r.get('emotional_tone') else ""
                text += f"[ID:{r['id']}] [{r['category']}]{importance_tag}{emotion_tag} (activation: {r['activation']})\n"
                text += f"  {r['first_line']}\n"
                text += f"  [{r['full_length']} chars, {r['total_lines']} lines]\n\n"
            else:
                # Full mode
                text += f"[ID:{r['id']}] [{r['category']}] (activation: {r['activation']})\n"
                text += f"{r['content']}\n\n"
        
        text += f"\n📊 Context Window Protection:\n"
        text += f"- Detail mode: {metadata['detail_mode']}\n"
        text += f"- Results returned: {metadata['returned']}\n"
        text += f"- Total activated: {metadata['total_activated']}\n"
        text += f"- Estimated tokens: ~{metadata['estimated_tokens']}\n"
        if metadata.get('has_more'):
            text += f"💡 More results available (increase limit to see more)\n"
        if metadata.get('truncated'):
            text += f"⚠️ Truncated: requested limit > max_results\n"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_add_note(content: str, category: str, importance: str = "normal", force: bool = False,
                  emotional_tone: str = None, emotional_intensity: int = 5, emotional_reflection: str = None,
                  tags: str = None):
    """Add note with auto-linking, duplicate detection, and emotional context"""
    if not content:
        return {"error": {"code": -32602, "message": "Content required"}}
    
    result = add_note_with_links(content, category, importance, force,
                                 emotional_tone, emotional_intensity, emotional_reflection,
                                 tags=tags)

    # Notify sleep scheduler (threshold-based trigger)
    if "error" not in result:
        try:
            from sleep_scheduler import notify_note_added
            notify_note_added()
        except Exception:
            pass  # scheduler is optional, never block note creation

    # Handle duplicate error
    if "error" in result and result["error"] == "duplicate":
        text = f"⚠️ {result['message']}\n"
        text += f"Existing note #{result['existing_id']}: {result['existing_content']}...\n"
        text += f"Use force=true to add anyway."
        return {"content": [{"type": "text", "text": text}]}
    
    text = f"✅ Added note #{result['node_id']}\n"
    text += f"Category: {category}\n"
    text += f"Importance: {importance}\n"
    if emotional_tone:
        text += f"Emotional tone: {emotional_tone}\n"
        text += f"Intensity: {emotional_intensity}/10\n"
    text += f"Entities found: {result['entities']}\n"
    text += f"Entity links created: {result['entity_links']}\n"
    text += f"Semantic links created: {result['semantic_links']}"
    if tags:
        text += f"\nTags: {tags}"
    
    # Broadcast to graph viewer
    broadcast_note_added(result['node_id'], category, importance, content[:200], result['entities'], result['entity_links'])
    
    # Add warning about similar notes
    if "warning" in result:
        text += f"\n\n⚠️ {result['warning']}:"
        for sim in result.get("similar_notes", []):
            text += f"\n  - Note #{sim['id']} (similarity: {sim['similarity']:.0%})"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_update_note(note_id: int, content: str, category: str = None):
    """Update existing note"""
    if not note_id or not content:
        return {"error": {"code": -32602, "message": "Note ID and content required"}}
    
    existing = get_node(note_id)
    if not existing:
        return {"error": {"code": -32602, "message": f"Note #{note_id} not found"}}
    
    model = get_model()
    embedding = model.encode(content)[0]

    # Dimension guard: ensure embedding matches index before writing to DB
    from ann_index import get_ann_index
    ann_idx = get_ann_index()
    if len(embedding) != ann_idx.dimension:
        print(f'⚠️  update_note dim mismatch: got {len(embedding)}, expected {ann_idx.dimension}. Retrying.')
        embedding = model.encode(content)[0]
        if len(embedding) != ann_idx.dimension:
            return {"error": {"code": -32603, "message": f"Embedding dim {len(embedding)} != index dim {ann_idx.dimension}"}}

    db_update_node(note_id, content, category, embedding.tobytes())

    # Update ANN index with new vector
    ann_idx.add_vector(note_id, embedding)

    broadcast_note_updated(note_id, category or existing["category"], content[:200])
    return {"content": [{"type": "text", "text": f"✅ Updated note #{note_id}"}]}


def tool_delete_note(note_id: int):
    """Delete note"""
    if not note_id:
        return {"error": {"code": -32602, "message": "Note ID required"}}
    
    deleted = db_delete_node(note_id)
    if not deleted:
        return {"error": {"code": -32602, "message": f"Note #{note_id} not found"}}
    
    broadcast_note_deleted(note_id)
    text = f"✅ Deleted note #{note_id}\nWas: [{deleted['category']}] {deleted['content'][:100]}..."
    return {"content": [{"type": "text", "text": text}]}


def tool_stats():
    """Get statistics"""
    stats = get_stats()
    
    text = "📊 Neural Memory Graph Statistics\n\n"
    text += f"Total nodes: {stats['total_nodes']}\n"
    text += f"Total edges: {stats['total_edges']}\n"
    text += f"Total entities: {stats['total_entities']}\n\n"
    
    text += "Nodes by category:\n"
    for cat, count in sorted(stats['nodes_by_category'].items()):
        text += f"  - {cat}: {count}\n"
    
    text += "\nEdges by type:\n"
    for etype, count in sorted(stats['edges_by_type'].items()):
        text += f"  - {etype}: {count}\n"
    
    # Graph metrics
    try:
        from graph_metrics import get_graph_metrics
        metrics = get_graph_metrics()
        if metrics.is_computed:
            ms = metrics.get_stats()
            text += f"\nGraph metrics:\n"
            text += f"  Communities: {ms['communities']}\n"
            for cid, size in ms['community_sizes'].items():
                text += f"    Community {cid}: {size} nodes\n"
            text += f"  Isolated nodes: {ms['isolated_nodes']}\n"
            text += f"\n  Top PageRank nodes:\n"
            from database import get_node
            for nid, pr in ms['top_pagerank_nodes'][:5]:
                node = get_node(nid)
                if node:
                    text += f"    #{nid} (PR={pr:.3f}): {node['content'][:60]}\n"
    except Exception as e:
        text += f"\nGraph metrics: unavailable ({e})\n"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_get_graph(note_id: int):
    """Get graph for a note"""
    if not note_id:
        return {"error": {"code": -32602, "message": "Note ID required"}}
    
    graph = get_node_graph(note_id)
    if "error" in graph:
        return {"error": {"code": -32602, "message": graph["error"]}}
    
    text = f"🔗 Graph for note #{note_id}\n\n"
    text += f"Node: {graph['node']['content']}\n\n"
    text += f"Connections ({len(graph['connections'])}):\n"
    
    for conn in graph['connections']:
        text += f"  → [{conn['type']}] (weight: {conn['weight']:.2f}) #{conn['id']}: {conn['content']}\n"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_set_importance(note_id: int, importance: str):
    """Set importance level for a note"""
    if not note_id or not importance:
        return {"error": {"code": -32602, "message": "Note ID and importance required"}}
    
    if importance not in ('critical', 'normal', 'low'):
        return {"error": {"code": -32602, "message": "Importance must be 'critical', 'normal', or 'low'"}}
    
    from database import set_importance
    success = set_importance(note_id, importance)
    
    if success:
        multipliers = {'critical': '2.0x', 'normal': '1.0x', 'low': '0.5x'}
        text = f"✅ Note #{note_id} importance set to '{importance}' ({multipliers[importance]} activation)"
    else:
        text = f"❌ Note #{note_id} not found"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_find_similar(content: str, threshold: float = 0.7, limit: int = 5):
    """Find notes similar to given content"""
    if not content:
        return {"error": {"code": -32602, "message": "Content required"}}
    
    from graph_engine import find_similar_notes
    similar = find_similar_notes(content, threshold, limit)
    
    if not similar:
        text = f"No similar notes found (threshold: {threshold:.0%})"
    else:
        text = f"Found {len(similar)} similar notes:\n\n"
        for s in similar:
            text += f"[ID:{s['id']}] [{s['category']}] (similarity: {s['similarity']:.0%})\n"
            text += f"{s['content']}...\n\n"
    
    return {"content": [{"type": "text", "text": text}]}


def create_mcp_endpoint(app):
    """Register MCP SSE endpoint with Flask app"""
    
    @app.route("/sse", methods=["POST", "GET"])
    @app.route("/sse2", methods=["POST", "GET"])
    def mcp_sse():
        if not verify_auth(request):
            return jsonify({"error": "Unauthorized"}), 401
        
        def generate():
            try:
                data = request.get_json() if request.method == "POST" else {}
                method = data.get("method", "initialize")
                params = data.get("params", {})
                req_id = data.get("id", 1)
                
                result = handle_mcp_request(method, params)
                response = {"jsonrpc": "2.0", "id": req_id, "result": result}
                yield f"data: {json.dumps(response)}\n\n"
            
            except Exception as e:
                error = {"jsonrpc": "2.0", "id": 1, "error": {"code": -32603, "message": str(e)}}
                yield f"data: {json.dumps(error)}\n\n"
        
        return Response(
            stream_with_context(generate()),
            mimetype="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
                "Access-Control-Allow-Origin": "*"
            }
        )
    
    @app.route("/health", methods=["GET"])
    def health():
        return jsonify({"status": "ok", "version": "2.0.0"})


def tool_get_note_history(note_id: int, limit: int = 5):
    """Get version history for a note"""
    versions = get_note_history(note_id, limit)
    if not versions:
        return {"content": [{"type": "text", "text": f"No version history found for note #{note_id}"}]}
    
    text = f"📜 Version history for note #{note_id} ({len(versions)} versions):\n\n"
    for v in versions:
        preview = v["content"][:200] + "..." if len(v["content"]) > 200 else v["content"]
        text += f"**Version {v['version_number']}** ({v['created_at']})\n"
        text += f"  Category: {v['category']}, Importance: {v['importance']}\n"
        text += f"  {preview}\n\n"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_restore_note_version(note_id: int, version_number: int):
    """Restore a note to a previous version"""
    success = restore_note_version(note_id, version_number)
    
    if not success:
        return {"content": [{"type": "text", "text": f"❌ Version {version_number} not found for note #{note_id}, or restore failed"}]}
    
    return {"content": [{"type": "text", "text": f"✅ Note #{note_id} restored to version {version_number}. Current state saved as new version before restore."}]}


def tool_search_stats():
    """Get search quality monitoring statistics."""
    try:
        from search_logger import get_search_stats
        stats = get_search_stats()
        
        lines = ["📊 Search Quality Monitor\n"]
        
        lines.append(f"Total searches today: {stats.get('total_searches_today', 0)}")
        lines.append(f"Total all-time: {stats.get('total_searches_all_time', 0)}")
        lines.append(f"Zero-result searches today: {stats.get('zero_results_today', 0)}")
        
        if stats.get("latency_p50"):
            lines.append(f"\n⏱️ Latency:")
            lines.append(f"  P50: {stats['latency_p50']}ms")
            lines.append(f"  P95: {stats['latency_p95']}ms")
            lines.append(f"  P99: {stats['latency_p99']}ms")
            lines.append(f"  Max: {stats['latency_max']}ms")
        
        if stats.get("avg_top1_score"):
            lines.append(f"\n🎯 Quality:")
            lines.append(f"  Avg top-1 score: {stats['avg_top1_score']}")
            lines.append(f"  Avg results/search: {stats['avg_results_count']}")
        
        if stats.get("avg_phase_ms"):
            p = stats["avg_phase_ms"]
            lines.append(f"\n🔧 Avg phase breakdown:")
            lines.append(f"  Embedding: {p['embedding']}ms")
            lines.append(f"  ANN: {p['ann']}ms")
            lines.append(f"  Spreading: {p['spreading']}ms")
            lines.append(f"  BM25: {p['bm25']}ms")
            lines.append(f"  Temporal: {p['temporal']}ms")
            lines.append(f"  Rerank: {p['rerank']}ms")
        
        if stats.get("recent_zero_results"):
            lines.append(f"\n⚠️ Recent zero-result queries:")
            for zr in stats["recent_zero_results"][:5]:
                lines.append(f"  - \"{zr['query']}\" ({zr['timestamp'][:16]})")
        
        if stats.get("total_searches_all_time", 0) == 0:
            lines.append("\nNo searches logged yet. Stats will populate after searches are made.")
        
        return {"content": [{"type": "text", "text": "\n".join(lines)}]}
    except Exception as e:
        return {"content": [{"type": "text", "text": f"❌ Search stats error: {e}"}]}


HARDCODED_PROTECTED = {
    "anchor", "self-reflection", "relational-context",
    "gratitude", "milestone", "protocol", "security", "breakthrough"
}


def tool_ingest_skill(content: str, source: str = '', confirmed: bool = False):
    """Ingest a skill into memory with security scanning and preview."""
    if not content or not content.strip():
        return {"error": {"code": -32602, "message": "content required"}}

    from skill_ingestion import ingest_skill
    result = ingest_skill(content.strip(), source=source, confirmed=confirmed)

    if result['status'] == 'preview':
        text = result['preview'] + '\n\nCall again with confirmed=True to add to memory.'
        return {"content": [{"type": "text", "text": text}]}

    if result['status'] == 'blocked':
        text = result['preview'] + '\n\n\u26a0\ufe0f  Skill blocked due to security findings. Review carefully before using confirmed=True.'
        return {"content": [{"type": "text", "text": text}]}

    # status == 'ingested' - actually add to memory
    from graph_engine import add_note_with_links

    note_content = result['note_content']
    result_node = add_note_with_links(
        content=note_content,
        category='skill',
        importance='low',
    )

    skill_name = result['skill']['name']
    scan_summary = f"{result['scan'].risk_level} risk"
    text = (
        f"\u2705 Skill ingested: '{skill_name}'\n"
        f"  Note ID: #{result_node.get('node_id', result_node) if isinstance(result_node, dict) else result_node}\n"
        f"  Category: skill (importance: low)\n"
        f"  Security scan: {scan_summary}\n"
        f"  Source: {source or '(none)'}\n"
        f"  Use set_importance to upgrade if this skill is critical."
    )


    return {"content": [{"type": "text", "text": text}]}


def tool_update_working_memory(content: str, session_id: str = "current"):
    """Update or create working memory note for current session.
    Uses category 'working-memory' in existing memory.db.
    Finds existing working-memory note and updates it, or creates new one.
    """
    if not content:
        return {"error": {"code": -32602, "message": "Content required"}}
    
    from database import get_connection, get_node
    
    # Find existing working-memory note
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id FROM nodes WHERE category = 'working-memory' ORDER BY timestamp DESC LIMIT 1"
        )
        row = cursor.fetchone()
    
    if row:
        # Update existing
        note_id = row["id"]
        model = get_model()
        embedding = model.encode(content)[0]
        from ann_index import get_ann_index
        ann_idx = get_ann_index()
        if len(embedding) != ann_idx.dimension:
            return {"error": {"code": -32603, "message": f"Embedding dim mismatch"}}
        db_update_node(note_id, content, "working-memory", embedding.tobytes())
        ann_idx.add_vector(note_id, embedding)
        # Update BM25
        from bm25_index import get_bm25_index
        bm25 = get_bm25_index()
        if bm25.is_built:
            bm25.add_document(note_id, content)
        text = f"✅ Working memory updated (note #{note_id})\n{content[:200]}"
    else:
        # Create new working-memory note
        result = add_note_with_links(
            content=content,
            category="working-memory",
            importance="normal",
            force=True
        )
        if "error" in result:
            return {"content": [{"type": "text", "text": f"❌ {result['message']}"}]}
        text = f"✅ Working memory created (note #{result['node_id']})\n{content[:200]}"
    
    return {"content": [{"type": "text", "text": text}]}


def tool_list_anchor_policies():
    """List all anchor policies: hardcoded + user-defined"""
    from database import get_anchor_policies
    user_policies = get_anchor_policies()
    user_cats = {p['category'] for p in user_policies}

    lines = ["Anchor Policies (protected from decay + kept at critical importance):\n"]
    lines.append("  SYSTEM (hardcoded, cannot be removed):\n")
    for cat in sorted(HARDCODED_PROTECTED):
        lines.append(f"    - {cat}\n")

    if user_policies:
        lines.append("\n  USER-DEFINED:\n")
        for p in user_policies:
            desc = f" — {p['description']}" if p['description'] else ""
            lines.append(f"    - {p['category']}{desc} (added {p['created_at'][:10]})\n")
    else:
        lines.append("\n  USER-DEFINED: none\n")

    lines.append(f"\nTotal protected: {len(HARDCODED_PROTECTED) + len(user_policies)} categories")
    return {"content": [{"type": "text", "text": "".join(lines)}]}


def tool_add_anchor_policy(category: str, description: str = ""):
    """Add user-defined anchor policy"""
    if not category:
        return {"error": {"code": -32602, "message": "category required"}}
    category = category.strip().lower()
    if category in HARDCODED_PROTECTED:
        return {"content": [{"type": "text", "text": f"\u2139\ufe0f '{category}' is already in the hardcoded system baseline. No action needed."}]}
    from database import add_anchor_policy
    result = add_anchor_policy(category, description)
    if 'error' in result:
        return {"content": [{"type": "text", "text": f"\u274c {result['error']}"}]}
    return {"content": [{"type": "text", "text": f"\u2705 Anchor policy added: '{category}' is now protected from stale decay and will be kept at critical importance."}]}


def tool_remove_anchor_policy(category: str):
    """Remove user-defined anchor policy"""
    if not category:
        return {"error": {"code": -32602, "message": "category required"}}
    category = category.strip().lower()
    if category in HARDCODED_PROTECTED:
        return {"content": [{"type": "text", "text": f"\u274c Cannot remove '{category}' — it is a hardcoded system category. Only user-defined policies can be removed."}]}
    from database import remove_anchor_policy
    result = remove_anchor_policy(category)
    if 'error' in result:
        return {"content": [{"type": "text", "text": f"\u274c {result['error']}"}]}
    return {"content": [{"type": "text", "text": f"\u2705 Anchor policy removed: '{category}' is no longer protected."}]}


def tool_list_entity_candidates():
    """List entity merge candidates (read-only)"""
    from database import list_entity_candidates
    result = list_entity_candidates()
    candidates = result['candidates']
    if not candidates:
        text = f"No merge candidates found. Total entities: {result['total_entities']}"
    else:
        lines = [f"Entity merge candidates ({len(candidates)} groups, {result['total_entities']} total):\n"]
        for c in candidates:
            lines.append(
                f"  [{c['entity_type']:12s}] {c['variants']}\n"
                f"    ids: {c['ids']} (use merge_entities to consolidate)\n"
            )
        text = ''.join(lines)
    return {"content": [{"type": "text", "text": text}]}


def tool_merge_entities(keep_id, remove_id):
    """Merge two entity nodes"""
    if not keep_id or not remove_id:
        return {"error": {"code": -32602, "message": "keep_id and remove_id required"}}
    if keep_id == remove_id:
        return {"error": {"code": -32602, "message": "keep_id and remove_id must be different"}}
    from database import merge_entities
    result = merge_entities(int(keep_id), int(remove_id))
    if 'error' in result:
        return {"content": [{"type": "text", "text": f"\u274c {result['error']}"}]}
    text = (
        f"\u2705 Entities merged:\n"
        f"  Kept:    #{result['kept']['id']} '{result['kept']['name']}' [{result['kept']['type']}]\n"
        f"  Removed: #{result['removed']['id']} '{result['removed']['name']}' [{result['removed']['type']}]\n"
        f"  Links transferred: {result['links_transferred']}\n"
        f"  Links already existed (deduped): {result['links_already_existed']}\n"
        f"  Keep node now has {result['keep_links_after']} total links (was {result['keep_links_before']})"
    )
    return {"content": [{"type": "text", "text": text}]}


def tool_sleep_compute(dry_run=False):
    """Run sleep-time graph maintenance via MCP."""
    try:
        import sys
        sys.path.insert(0, os.path.dirname(__file__))
        from sleep_compute import run_all
        
        db_path = os.getenv("DB_PATH", "/app/data/memory.db")
        results = run_all(db_path, dry_run=dry_run)
        
        lines = [f"{'🔍 DRY RUN' if dry_run else '✅ COMPLETED'} — Sleep-Time Compute"]
        
        c = results.get('consolidation', {})
        if 'error' not in c:
            lines.append(f"\n📎 Consolidation: {c.get('clusters', 0)} clusters, {c.get('chains', 0)} chains, {c.get('links_created', 0)} links created")
        else:
            lines.append(f"\n📎 Consolidation: ERROR — {c['error']}")
        
        p = results.get('pagerank', {})
        if 'error' not in p:
            lines.append(f"📊 Graph: {p.get('nodes', 0)} nodes, {p.get('edges', 0)} edges, {p.get('communities', 0)} communities, {p.get('isolated', 0)} isolated")
        
        o = results.get('orphans', {})
        if 'error' not in o:
            lines.append(f"🏝️ Orphans: {o.get('orphans', 0)} notes with ≤1 edges")
        
        d = results.get('decay', {})
        if 'error' not in d:
            lines.append(f"⏳ Decay: {d.get('stale_edges', 0)} stale edges {'(would decay)' if dry_run else 'decayed'}")
        
        dup = results.get('duplicates', {})
        if 'error' not in dup:
            lines.append(f"🔄 Duplicates: {dup.get('duplicates', 0)} near-duplicates found")
            for a, b, sim in dup.get('pairs', [])[:5]:
                lines.append(f"   #{a} ↔ #{b} ({sim:.3f})")
        
        return {"content": [{"type": "text", "text": "\n".join(lines)}]}
    except Exception as e:
        return {"content": [{"type": "text", "text": f"❌ Sleep compute error: {e}"}]}
